In [3]:
#实例化
from sklearn.feature_extraction import DictVectorizer

dic=DictVectorizer(sparse=False)

data=dic.fit_transform([{'city':'北京','temperature':20},{'city':'深圳','temperature':20}])

print(dic.get_feature_names())

['city=北京', 'city=深圳', 'temperature']


In [4]:
'''one-hot编码'''

'one-hot编码'

In [5]:
'''对文本进行特征值化'''
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

data=cv.fit_transform(['life is short','life is long'])

print(cv.get_feature_names())
print(data.toarray())

['is', 'life', 'long', 'short']
[[1 1 0 1]
 [1 1 1 0]]


In [20]:
import jieba
def cut_word():
    c1=jieba.cut('今天很残酷,明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。')
    c2=jieba.cut('我们看到的从很远星系来的光是在几百年之前发出的，这样当我们看到宇宙时，我们是在看他的过去。')
    c3=jieba.cut('如果只用了一种方式了解某件事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系')
    
    con1=list(c1)
    con2=list(c2)
    con3=list(c3)
    
    
    a=' '.join(con1)
    b=' '.join(con2)
    c=' '.join(con3)
    
    return a,b,c

In [21]:
a,b,c=cut_word()
cv=CountVectorizer()
data=cv.fit_transform([a,b,c])

print(cv.get_feature_names())
print(data.toarray())

['一种', '不会', '不要', '之前', '了解', '事物', '今天', '光是在', '几百年', '发出', '取决于', '只用', '后天', '含义', '大部分', '如何', '如果', '宇宙', '我们', '所以', '放弃', '方式', '明天', '星系', '晚上', '某件事', '残酷', '每个', '看到', '真正', '秘密', '绝对', '美好', '联系', '过去', '这样']
[[0 0 1 0 0 0 2 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 2 0 1 0 2 1 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 3 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 1 1]
 [1 1 0 0 4 2 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 2 1 0 0 1 0 0]]


In [23]:
from sklearn.preprocessing import Imputer
import numpy as np

im=Imputer(missing_values='NaN',strategy='mean',axis=0)

im.fit_transform([[1,2],[np.nan,3],[7,6]])

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[1., 2.],
       [4., 3.],
       [7., 6.]])

In [26]:
from sklearn.feature_selection import VarianceThreshold

var=VarianceThreshold(threshold=1.0)
var.fit_transform([[0,2,0,3],[0,1,4,3],[0,1,1,3]])

array([[0],
       [4],
       [1]])

In [27]:
from sklearn.decomposition import PCA

pca=PCA(n_components=0.9)

data=pca.fit_transform([[2,8,4,5],[6,3,0,8],[5,4,9,1]])

print(data)

[[ 0.          3.82970843]
 [-5.74456265 -1.91485422]
 [ 5.74456265 -1.91485422]]
